### ISSUE TITLE
run_training() fails

### ISSUE THREAD

**Issue by ghost** [myfatemi04/VQA#1]
Traceback (most recent call last):
  File "answer_questions_for_image.py", line 117, in <module>
    run_training()
  File "answer_questions_for_image.py", line 64, in run_training
    loss = forward(model, *batch).loss
TypeError: forward() takes 3 positional arguments but 4 were given

**Comment by ghost** [comment]
I tried to leave a comment on youtube but it doesn't work (possibly due to proxy). I need to reproduce a VQA project as homework but I don't have much time now I sorry you have to hear this but can you share a copy of trained .pt checkpoint.

**Comment by myfatemi04** [comment]
Hey, try using the commit at https://github.com/myfatemi04/VQA/tree/1881d04dcb25a600e8ccb3a44a000397b57de72d
